version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binanceusbot
    restart: unless-stopped
    
    # Environment variables (use .env file)
    env_file:
      - .env
    
    # Port mapping
    ports:
      - "3000:3000"
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
    
    # Network
    networks:
      - botnet
    
    # Volumes (if needed for logs or data persistence)
    # volumes:
    #   - ./logs:/app/logs:rw

networks:
  botnet:
    driver: bridge

